=== anneliesdevesse/apex/bertha-lib/data/schema/experiment.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xml:lang="en-US"
    targetNamespace="http://med.kuleuven.be/exporl/bertha/1.0/experiment"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">

    <xs:element name="experiment">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="blocks" type="bertha:blockstype"/>
                <xs:element name="connections" type="bertha:connectionstype"/>
                <xs:element name="device" type="bertha:devicetype"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="blockstype">
        <xs:sequence>
            <xs:element name="block" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="plugin" type="xs:string"/>
                        <xs:element name="inputports" type="xs:int" minOccurs="0" maxOccurs="1"/>
                        <xs:element name="outputports" type="xs:int" minOccurs="0" maxOccurs="1"/>
                        <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="name" type="xs:string"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                        <!--<xs:any processContents="skip"/>-->
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:ID" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="connectionstype">
        <xs:sequence>
            <xs:element name="connection" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="from" type="bertha:fromtotype"/>
                        <xs:element name="to" type="bertha:fromtotype"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="fromtotype">
        <xs:attribute name="id" type="xs:IDREF" use="required"/>
        <xs:attribute name="port" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="devicetype">
        <xs:sequence>
            <xs:element name="driver" type="xs:string" />
            <xs:element name="samplerate" minOccurs="0" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:unsignedInt">
                        <xs:enumeration value="96000"/>
                        <xs:enumeration value="48000"/>
                        <xs:enumeration value="44100"/>
                        <xs:enumeration value="22050"/>
                        <xs:enumeration value="16000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="blocksize" type="xs:unsignedInt" minOccurs="0" maxOccurs="1"/>
            <xs:element name="playbackports" type="xs:int" minOccurs="1" maxOccurs="1"/>
            <xs:element name="captureports" type="xs:int" minOccurs="1" maxOccurs="1"/>
            <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="name" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <!--<xs:any processContents="skip"/>-->
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

</xs:schema>

=== anneliesdevesse/apex/bertha-lib/data/testexperiments/sin1000_sin50Hz-halfwavetest.xml
<?xml version="1.0" encoding="UTF-8"?>
<bertha:experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://med.kuleuven.be/exporl/bertha/1.0/experiment ../schema/experiment.xsd"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">
    <blocks>
        <block id="sineblock1">
            <plugin>SineGenerator</plugin>
            <parameter name="frequency">1000</parameter>
            <parameter name="amplitude">0.2</parameter>
            <parameter name="phase">0</parameter>
        </block>
        <block id="sineblock2">
            <plugin>SineGenerator</plugin>
            <parameter name="frequency">50</parameter>
            <parameter name="amplitude">0.2</parameter>
            <parameter name="phase">0</parameter>
        </block>
        <block id="rectificationblock">
            <plugin>Rectification</plugin>
        </block>
        <block id="multiplierblock">
            <plugin>Multiplier</plugin>
            <inputports>2</inputports>
        </block>
    </blocks>
    <connections>
        <connection>
            <from id="sineblock1" port="output-1"/>
            <to id="multiplierblock" port="input-1"/>
        </connection>
        <connection>
            <from id="sineblock2" port="output-1"/>
            <to id="rectificationblock" port="input-1"/>
        </connection>
        <connection>
            <from id="rectificationblock" port="output-1"/>
            <to id="multiplierblock" port="input-2"/>
        </connection>
        <connection>
            <from id="multiplierblock" port="output-1"/>
            <to id="device" port="playback-1"/>
        </connection>
    </connections>
    <device id="device">
        <driver>File</driver>
        <samplerate>44100</samplerate>
        <blocksize>44100</blocksize>
        <playbackports>1</playbackports>
        <captureports>0</captureports>
        <parameter name="outputFile">OUTPUTFILEPLACEHOLDER</parameter>
    </device>
</bertha:experiment>

=== anneliesdevesse/apex/bertha-lib/data/testexperiments/threadedhrtfsignaltest.xml
<?xml version="1.0" encoding="UTF-8"?>
<bertha:experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://med.kuleuven.be/exporl/bertha/1.0/experiment ../schema/experiment.xsd"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">
    <blocks>
        <block id="hrtfSignal">
            <plugin>ThreadedFirFilter</plugin>
            <parameter name="filePath">../testdata/freedome_hrtf_GHB_0_5s_0deg_16000Hz_right.bin</parameter>
        </block>
    </blocks>
    <connections>
        <connection>
            <from id="device1" port="capture-1"/>
            <to id="hrtfSignal" port="input-1"/>
        </connection>
        <connection>
            <from id="hrtfSignal" port="output-1"/>
            <to id="device1" port="playback-1"/>
        </connection>
        <connection>
            <from id="hrtfSignal" port="output-2"/>
            <to id="device1" port="playback-2"/>
        </connection>
    </connections>
    <device id="device1">
        <driver>Files</driver>
        <samplerate>16000</samplerate>
        <blocksize>8192</blocksize>
        <playbackports>2</playbackports>
        <captureports>1</captureports>
        <parameter name="inputFiles">"../../../bertha-lib/data/testdata/man001.wav"</parameter>
        <parameter name="outputFiles">"../testdata/output_ch1.wav","../testdata/output_ch2.wav"</parameter>
    </device>
</bertha:experiment>

=== anneliesdevesse/apex/bertha-lib/data/testexperiments/fftfileexperiment.xml
<?xml version="1.0" encoding="UTF-8"?>
<bertha:experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://med.kuleuven.be/exporl/bertha/1.0/experiment ../schema/experiment.xsd"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">
    <blocks>
        <block id="fft">
            <plugin>Fft</plugin>
        </block>
        <block id="ifft">
            <plugin>Ifft</plugin>
        </block>
    </blocks>
    <connections>
        <connection>
            <from id="device" port="capture-1"/>
            <to id="fft" port="input-1"/>
        </connection>
        <connection>
            <from id="fft" port="output-1"/>
            <to id="ifft" port="input-1"/>
        </connection>
        <connection>
            <from id="ifft" port="output-1"/>
            <to id="device" port="playback-1"/>
        </connection>
    </connections>
    <device id="device">
        <driver>File</driver>
        <samplerate>44100</samplerate>
        <blocksize>441</blocksize>
        <playbackports>1</playbackports>
        <captureports>1</captureports>
        <parameter name="inputFile">INPUTFILEPLACEHOLDER</parameter>
        <parameter name="outputFile">OUTPUTFILEPLACEHOLDER</parameter>
    </device>
</bertha:experiment>

=== anneliesdevesse/apex/bertha-lib/data/testexperiments/filesinktest.xml
<?xml version="1.0" encoding="UTF-8"?>
<bertha:experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://med.kuleuven.be/exporl/bertha/1.0/experiment ../schema/experiment.xsd"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">
    <blocks>
        <block id="block">
            <plugin>FileSink</plugin>
            <parameter name="filePath">../testdata/output_ch1.wav</parameter>
            <parameter name="format">pcm16</parameter>
        </block>
    </blocks>
    <connections>
        <connection>
            <from id="device" port="capture-1"/>
            <to id="block" port="input-1"/>
        </connection>
        <connection>
            <from id="block" port="output-1"/>
            <to id="device" port="playback-1"/>
        </connection>
    </connections>
    <device id="device">
        <driver>Files</driver>
        <samplerate>16000</samplerate>
        <blocksize>8192</blocksize>
        <playbackports>1</playbackports>
        <captureports>1</captureports>
        <parameter name="inputFiles">../testdata/man001.wav</parameter>
        <parameter name="outputFiles">../testdata/output.wav</parameter>
    </device>
</bertha:experiment>

=== anneliesdevesse/apex/bertha-lib/data/testexperiments/gaintest.xml
<?xml version="1.0" encoding="UTF-8"?>
<bertha:experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://med.kuleuven.be/exporl/bertha/1.0/experiment ../schema/experiment.xsd"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">
    <blocks>
        <block id="block">
            <plugin>Gain</plugin>
            <parameter name="gain">6</parameter>
        </block>
    </blocks>
    <connections>
        <connection>
            <from id="block" port="output-1"/>
            <to id="device" port="playback-1"/>
        </connection>
        <connection>
            <from id="device" port="capture-1"/>
            <to id="block" port="input-1"/>
        </connection>
    </connections>
    <device id="device">
        <driver>File</driver>
        <samplerate>44100</samplerate>
        <blocksize>44100</blocksize>
        <playbackports>1</playbackports>
        <captureports>1</captureports>
        <parameter name="inputFile">INPUTFILEPLACEHOLDER</parameter>
        <parameter name="outputFile">OUTPUTFILEPLACEHOLDER</parameter>
    </device>
</bertha:experiment>

=== anneliesdevesse/apex/bertha-lib/data/testexperiments/adapttest_10.xml
<?xml version="1.0" encoding="UTF-8"?>
<bertha:experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://med.kuleuven.be/exporl/bertha/1.0/experiment ../schema/experiment.xsd"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">
    <blocks>
        <block id="beamformer">
            <plugin>Beamformer</plugin>
            <parameter name="filePath">../testdata/FB_freedom_10.bin</parameter>
        </block>
        <block id="beamformersnr">
            <plugin>Beamformer</plugin>
            <parameter name="filePath">../testdata/FB_freedom_10.bin</parameter>
        </block>
        <block id="deemphasissignal">
            <plugin>Emphasis</plugin>
            <parameter name="filePath">../testdata/filter_deemph.bin</parameter>
        </block>
        <block id="deemphasisvad">
            <plugin>Emphasis</plugin>
            <parameter name="filePath">../testdata/filter_deemph.bin</parameter>
        </block>
        <block id="vad">
            <plugin>Vad</plugin>
            <parameter name="length">512</parameter>
        </block>
        <block id="amplifier">
            <plugin>Amplifier</plugin>
            <inputports>2</inputports>
            <outputports>2</outputports>
            <parameter name="baseGain">15.7378580971083245</parameter>
            <parameter name="gain">-10</parameter>
        </block>
        <block id="offsetamplifier">
            <plugin>Amplifier</plugin>
            <inputports>2</inputports>
            <outputports>2</outputports>
            <parameter name="gain">10</parameter>
        </block>
        <block id="adaptivewiener">
            <plugin>AdaptiveWienerFilter</plugin>
            <parameter name="length">64</parameter>
            <parameter name="muInv">0</parameter>
        </block>
        <block id="summation1">
            <plugin>Summation</plugin>
        </block>
        <block id="summation2">
            <plugin>Summation</plugin>
        </block>
        <block id="summation3">
            <plugin>Summation</plugin>
        </block>
        <block id="summation4">
            <plugin>Summation</plugin>
        </block>
    </blocks>
    <connections>
        <connection>
            <from id="device1" port="capture-1"/>
            <to id="amplifier" port="input-1"/>
        </connection>
        <connection>
            <from id="device1" port="capture-2"/>
            <to id="amplifier" port="input-2"/>
        </connection>
        <connection>
            <from id="amplifier" port="output-1"/>
            <to id="offsetamplifier" port="input-1"/>
        </connection>
        <connection>
            <from id="amplifier" port="output-2"/>
            <to id="offsetamplifier" port="input-2"/>
        </connection>

        <connection>
            <from id="amplifier" port="output-1"/>
            <to id="summation1" port="input-1"/>
        </connection>
        <connection>
            <from id="amplifier" port="output-2"/>
            <to id="summation2" port="input-1"/>
        </connection>
        <connection>
            <from id="offsetamplifier" port="output-1"/>
            <to id="summation3" port="input-1"/>
        </connection>
        <connection>
            <from id="offsetamplifier" port="output-2"/>
            <to id="summation4" port="input-1"/>
        </connection>
        <connection>
            <from id="device1" port="capture-3"/>
            <to id="summation1" port="input-2"/>
        </connection>
        <connection>
            <from id="device1" port="capture-4"/>
            <to id="summation2" port="input-2"/>
        </connection>
        <connection>
            <from id="device1" port="capture-3"/>
            <to id="summation3" port="input-2"/>
        </connection>
        <connection>
            <from id="device1" port="capture-4"/>
            <to id="summation4" port="input-2"/>
        </connection>

        <connection>
            <from id="summation1" port="output-1"/>
            <to id="beamformer" port="input-1"/>
        </connection>
        <connection>
            <from id="summation2" port="output-1"/>
            <to id="beamformer" port="input-2"/>
        </connection>
        <connection>
            <from id="summation3" port="output-1"/>
            <to id="beamformersnr" port="input-1"/>
        </connection>
        <connection>
            <from id="summation4" port="output-1"/>
            <to id="beamformersnr" port="input-2"/>
        </connection>
        <connection>
            <from id="beamformersnr" port="output-1"/>
            <to id="deemphasisvad" port="input-1"/>
        </connection>
        <connection>
            <from id="beamformersnr" port="output-2"/>
            <to id="deemphasisvad" port="input-2"/>
        </connection>
        <connection>
            <from id="deemphasisvad" port="output-1"/>
            <to id="vad" port="input-1"/>
        </connection>
        <connection>
            <from id="deemphasisvad" port="output-2"/>
            <to id="vad" port="input-2"/>
        </connection>
        <connection>
            <from id="beamformer" port="output-1"/>
            <to id="adaptivewiener" port="input-1"/>
        </connection>
        <connection>
            <from id="beamformer" port="output-2"/>
            <to id="adaptivewiener" port="input-2"/>
        </connection>
        <connection>
            <from id="beamformersnr" port="output-1"/>
            <to id="adaptivewiener" port="input-3"/>
        </connection>
        <connection>
            <from id="beamformersnr" port="output-2"/>
            <to id="adaptivewiener" port="input-4"/>
        </connection>
        <connection>
            <from id="vad" port="output-1"/>
            <to id="adaptivewiener" port="input-5"/>
        </connection>
        <connection>
            <from id="adaptivewiener" port="output-1"/>
            <to id="deemphasissignal" port="input-1"/>
        </connection>
        <connection>
            <from id="adaptivewiener" port="output-2"/>
            <to id="deemphasissignal" port="input-2"/>
        </connection>
        <connection>
            <from id="deemphasissignal" port="output-1"/>
            <to id="device1" port="playback-1"/>
        </connection>
        <connection>
            <from id="deemphasissignal" port="output-2"/>
            <to id="device1" port="playback-2"/>
        </connection>
    </connections>
    <device id="device1">
        <driver>Files</driver>
        <samplerate>16000</samplerate>
        <blocksize>8192</blocksize>
        <playbackports>2</playbackports>
        <captureports>4</captureports>
        <parameter name="inputFiles">../testdata/adept_signal_ch1.wav,../testdata/adept_signal_ch2.wav,../testdata/adept_noise_ch1.wav,../testdata/adept_noise_ch2.wav</parameter>
        <parameter name="outputFiles">../testdata/output_ch1.wav,../testdata/output_ch2.wav</parameter>
    </device>
</bertha:experiment>
