=== anneliesdevesse/apex/bertha-lib/data/schema/experiment.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xml:lang="en-US"
    targetNamespace="http://med.kuleuven.be/exporl/bertha/1.0/experiment"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">

    <xs:element name="experiment">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="blocks" type="bertha:blockstype"/>
                <xs:element name="connections" type="bertha:connectionstype"/>
                <xs:element name="device" type="bertha:devicetype"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="blockstype">
        <xs:sequence>
            <xs:element name="block" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="plugin" type="xs:string"/>
                        <xs:element name="inputports" type="xs:int" minOccurs="0" maxOccurs="1"/>
                        <xs:element name="outputports" type="xs:int" minOccurs="0" maxOccurs="1"/>
                        <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="name" type="xs:string"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                        <!--<xs:any processContents="skip"/>-->
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:ID" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="connectionstype">
        <xs:sequence>
            <xs:element name="connection" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="from" type="bertha:fromtotype"/>
                        <xs:element name="to" type="bertha:fromtotype"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="fromtotype">
        <xs:attribute name="id" type="xs:IDREF" use="required"/>
        <xs:attribute name="port" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="devicetype">
        <xs:sequence>
            <xs:element name="driver" type="xs:string" />
            <xs:element name="samplerate" minOccurs="0" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:unsignedInt">
                        <xs:enumeration value="96000"/>
                        <xs:enumeration value="48000"/>
                        <xs:enumeration value="44100"/>
                        <xs:enumeration value="22050"/>
                        <xs:enumeration value="16000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="blocksize" type="xs:unsignedInt" minOccurs="0" maxOccurs="1"/>
            <xs:element name="playbackports" type="xs:int" minOccurs="1" maxOccurs="1"/>
            <xs:element name="captureports" type="xs:int" minOccurs="1" maxOccurs="1"/>
            <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="name" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <!--<xs:any processContents="skip"/>-->
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

</xs:schema>

=== anneliesdevesse/apex/bertha-lib/data/testexperiments/mixerexperiment.xml
<?xml version="1.0" encoding="UTF-8"?>
<bertha:experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://med.kuleuven.be/exporl/bertha/1.0/experiment ../schema/experiment.xsd"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">
    <blocks>
        <block id="sineblock1">
            <plugin>SineGenerator</plugin>
            <parameter name="frequency">1000</parameter>
            <parameter name="amplitude">0.2</parameter>
        <parameter name="phase">0</parameter>
        </block>
        <block id="sineblock2">
            <plugin>SineGenerator</plugin>
            <parameter name="frequency">50</parameter>
            <parameter name="amplitude">0.2</parameter>
            <parameter name="phase">0</parameter>
        </block>
        <block id="switchblock">
            <plugin>Mixer</plugin>
            <inputports>2</inputports>
            <outputports>2</outputports>
        </block>
    </blocks>
    <connections>
        <connection>
            <from id="sineblock1" port="output-1"/>
            <to id="switchblock" port="input-1"/>
        </connection>
        <connection>
            <from id="sineblock2" port="output-1"/>
            <to id="switchblock" port="input-2"/>
        </connection>
        <connection>
            <from id="switchblock" port="output-1"/>
            <to id="device" port="playback-1"/>
        </connection>
        <connection>
            <from id="switchblock" port="output-2"/>
            <to id="device" port="playback-2"/>
        </connection>
    </connections>
    <device id="device">
        <driver>Files</driver>
        <samplerate>44100</samplerate>
        <blocksize>44100</blocksize>
        <playbackports>2</playbackports>
        <captureports>0</captureports>
        <parameter name="outputFiles">OUTPUTFILEPLACEHOLDER</parameter>
    </device>
</bertha:experiment>

=== anneliesdevesse/apex/bertha-lib/data/testexperiments/typeexperiment.xml
<?xml version="1.0" encoding="UTF-8"?>
<bertha:experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://med.kuleuven.be/exporl/bertha/1.0/experiment ../schema/experiment.xsd"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">
    <blocks>
        <block id="block1">
            <plugin>TypeTesting</plugin>
            <parameter name="m_int">1234</parameter>
            <parameter name="m_float">11.1111</parameter>
            <parameter name="m_double">2222.222</parameter>
            <parameter name="m_stringList">"ene","nog ene","IET \"moeilijker\",comma","\\en wa\tnu"</parameter>
            <parameter name="m_vector">[0.1 1.23 2 3.115]</parameter>
            <parameter name="m_doubleVector">[[0.1][2.3 3][4.3 -2.345]]</parameter>
            <parameter name="m_bool">false</parameter>
            <parameter name="m_enum">One</parameter>
        </block>
        <block id="block2">
            <plugin>TypeTesting</plugin>
            <parameter name="m_stringList">gewoon,comma's,mag,ook</parameter>
            <parameter name="m_vector">[0.1  1.23   2 3.115]</parameter>
            <parameter name="m_doubleVector">  [0.1   ;  2.3   3;4.3 -2.345] </parameter>
            <parameter name="m_bool">0</parameter>
            <parameter name="m_enum">1</parameter>
        </block>
    </blocks>
    <connections>
        <connection>
            <from id="block1" port="output-1"/>
            <to id="block2" port="input-1"/>
        </connection>
        <connection>
            <from id="block2" port="output-1"/>
            <to id="device" port="playback-1"/>
        </connection>
    </connections>
    <device id="device">
        <driver>File</driver>
        <samplerate>44100</samplerate>
        <blocksize>44100</blocksize>
        <playbackports>1</playbackports>
        <captureports>0</captureports>
    </device>
</bertha:experiment>

=== anneliesdevesse/apex/bertha-lib/data/testexperiments/compressorexperiment.xml
<?xml version="1.0" encoding="UTF-8"?>
<bertha:experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://med.kuleuven.be/exporl/bertha/1.0/experiment ../schema/experiment.xsd"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">
    <blocks>
        <block id="block">
            <plugin>Compressor</plugin>
            <parameter name="rmsWindowLength">20</parameter>
            <parameter name="calibrationValue">113</parameter>
            <parameter name="attackTime">30</parameter>
            <parameter name="releaseTime">600</parameter>
            <parameter name="xBreakPoints">[20 40 80]</parameter>
            <parameter name="yBreakPoints">[60 80 90]</parameter>
        </block>
    </blocks>
    <connections>
        <connection>
            <from id="device" port="capture-1"/>
            <to id="block" port="input-1"/>
        </connection>
        <connection>
            <from id="block" port="output-1"/>
            <to id="device" port="playback-1"/>
        </connection>
    </connections>
    <device id="device">
        <driver>File</driver>
        <samplerate>44100</samplerate>
        <blocksize>2048</blocksize>
        <playbackports>1</playbackports>
        <captureports>1</captureports>
        <parameter name="inputFile">INPUTFILEPLACEHOLDER</parameter>
        <parameter name="outputFile">OUTPUTFILEPLACEHOLDER</parameter>
    </device>
</bertha:experiment>

=== anneliesdevesse/apex/bertha-lib/data/testexperiments/constraintsexperiment.xml
<?xml version="1.0" encoding="UTF-8"?>
<bertha:experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://med.kuleuven.be/exporl/bertha/1.0/experiment ../schema/experiment.xsd"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">
    <blocks>
        <block id="block1">
            <plugin>TypeTesting</plugin>
            <parameter name="m_int">20000</parameter>
            <parameter name="m_float">-15000</parameter>
            <parameter name="m_double">22000</parameter>
            <parameter name="m_vector">[101 5 22 -200]</parameter>
            <parameter name="m_doubleVector">[[101][5 22][-200 2.345]]</parameter>
            <parameter name="m_bool">false</parameter>
            <parameter name="m_enum">One</parameter>
        </block>
    </blocks>
    <connections>
        <connection>
            <from id="block1" port="output-1"/>
            <to id="device" port="playback-1"/>
        </connection>
    </connections>
    <device id="device">
        <driver>File</driver>
        <samplerate>44100</samplerate>
        <blocksize>44100</blocksize>
        <playbackports>1</playbackports>
        <captureports>0</captureports>
    </device>
</bertha:experiment>

=== anneliesdevesse/apex/bertha-lib/data/testexperiments/dummyexperiment.xml
<?xml version="1.0" encoding="UTF-8"?>
<bertha:experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://med.kuleuven.be/exporl/bertha/1.0/experiment ../schema/experiment.xsd"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">
    <blocks>
        <block id="leaf1">
            <plugin>SineGenerator</plugin>
            <parameter name="frequency">1000</parameter>
            <parameter name="amplitude">0.2</parameter>
            <parameter name="phase">0</parameter>
        </block>
        <block id="leaf2">
            <plugin>SineGenerator</plugin>
            <parameter name="frequency">1000</parameter>
            <parameter name="amplitude">0.2</parameter>
            <parameter name="phase">0</parameter>
        </block>
        <block id="amplifier">
            <plugin>Amplifier</plugin>
            <inputports>2</inputports>
            <outputports>2</outputports>
            <parameter name="baseGain">-10</parameter>
            <parameter name="gain">0</parameter>
        </block>
        <block id="summation">
            <plugin>Summation</plugin>
        </block>
    </blocks>

    <connections>
        <connection>
            <from id="device" port="capture-1"/>
            <to id="summation" port="input-1"/>
        </connection>

        <connection>
            <from id="leaf1" port="output-1"/>
            <to id="summation" port="input-2"/>
        </connection>
        <connection>
            <from id="leaf2" port="output-1"/>
            <to id="amplifier" port="input-1"/>
        </connection>

        <connection>
            <from id="summation" port="output-1"/>
            <to id="device" port="playback-1"/>
        </connection>
        <connection>
            <from id="amplifier" port="output-1"/>
            <to id="device" port="playback-2"/>
        </connection>
    </connections>

    <device id="device">
        <driver>Files</driver>
        <samplerate>16000</samplerate>
        <blocksize>8192</blocksize>
        <playbackports>2</playbackports>
        <captureports>1</captureports>
        <parameter name="inputFiles">../testdata/man001.wav</parameter>
        <parameter name="outputFiles">%OUTPUTFILEPLACEHOLDER%</parameter>
    </device>
</bertha:experiment>

=== anneliesdevesse/apex/bertha-lib/data/testexperiments/sin1000Hztest.xml
<?xml version="1.0" encoding="UTF-8"?>
<bertha:experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://med.kuleuven.be/exporl/bertha/1.0/experiment ../schema/experiment.xsd"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">
    <blocks>
        <block id="block">
            <plugin>SineGenerator</plugin>
            <parameter name="frequency">1000</parameter>
            <parameter name="amplitude">0.2</parameter>
            <parameter name="phase">0</parameter>
        </block>
    </blocks>
    <connections>
        <connection>
            <from id="block" port="output-1"/>
            <to id="device" port="playback-1"/>
        </connection>
    </connections>
    <device id="device">
        <driver>File</driver>
        <samplerate>44100</samplerate>
        <blocksize>44100</blocksize>
        <playbackports>1</playbackports>
        <captureports>0</captureports>
        <parameter name="outputFile">OUTPUTFILEPLACEHOLDER</parameter>
    </device>
</bertha:experiment>

=== anneliesdevesse/apex/bertha-lib/data/testexperiments/olafftexperiment.xml
<?xml version="1.0" encoding="UTF-8"?>
<bertha:experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://med.kuleuven.be/exporl/bertha/1.0/experiment ../schema/experiment.xsd"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">
    <blocks>
        <block id="fftblock">
            <plugin>OlaFft</plugin>
            <parameter name="fftLength">2048</parameter>
        </block>
        <block id="ifftblock">
            <plugin>OlaIfft</plugin>
            <parameter name="fftLength">2048</parameter>
        </block>
    </blocks>
    <connections>
        <connection>
            <from id="device" port="capture-1"/>
            <to id="fftblock" port="input-1"/>
        </connection>
        <connection>
            <from id="fftblock" port="output-1"/>
            <to id="ifftblock" port="input-1"/>
        </connection>
        <connection>
            <from id="ifftblock" port="output-1"/>
            <to id="device" port="playback-1"/>
        </connection>
    </connections>
    <device id="device">
        <driver>File</driver>
        <samplerate>44100</samplerate>
        <blocksize>512</blocksize>
        <playbackports>1</playbackports>
        <captureports>1</captureports>
        <parameter name="inputFile">INPUTFILEPLACEHOLDER</parameter>
        <parameter name="outputFile">OUTPUTFILEPLACEHOLDER</parameter>
    </device>
</bertha:experiment>

=== anneliesdevesse/apex/bertha-lib/data/testexperiments/wienertest.xml
<?xml version="1.0" encoding="UTF-8"?>
<bertha:experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://med.kuleuven.be/exporl/bertha/1.0/experiment ../schema/experiment.xsd"
    xmlns:bertha="http://med.kuleuven.be/exporl/bertha/1.0/experiment">
    <blocks>
        <block id="wiener">
            <plugin>WienerFilter</plugin>
            <parameter name="filePath">../testdata/GHB_0_5s_filter.bin</parameter>
        </block>
    </blocks>
    <connections>
        <connection>
            <from id="device1" port="capture-1"/>
            <to id="wiener" port="input-1"/>
        </connection>
        <connection>
            <from id="device1" port="capture-2"/>
            <to id="wiener" port="input-2"/>
        </connection>
        <connection>
            <from id="wiener" port="output-1"/>
            <to id="device1" port="playback-1"/>
        </connection>
        <connection>
            <from id="wiener" port="output-2"/>
            <to id="device1" port="playback-2"/>
        </connection>
    </connections>
    <device id="device1">
        <driver>Files</driver>
        <samplerate>16000</samplerate>
        <blocksize>8192</blocksize>
        <playbackports>2</playbackports>
        <captureports>2</captureports>
        <parameter name="inputFiles">../testdata/hrtf_signalnoisecombined_ch1.wav,../testdata/hrtf_signalnoisecombined_ch2.wav</parameter>
        <parameter name="outputFiles">../testdata/output_ch1.wav,../testdata/output_ch2.wav</parameter>
    </device>
</bertha:experiment>
