=== anneliesdevesse/apex/data/schemas/apexconfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xml:lang="en-US" 
        targetNamespace="http://med.kuleuven.be/exporl/apex/3.0.2/config"
        xmlns:apex="http://med.kuleuven.be/exporl/apex/3.0.2/config">
        
        <xs:annotation>
            <xs:documentation xml:lang="en-US">
                Apex main config file schema
            </xs:documentation>
        </xs:annotation>
        
        <xs:complexType name="drivernameType" mixed="true">
            <xs:attribute name="driver" type="xs:Name"  use="required"/>
        </xs:complexType>
        
        <xs:complexType name="soundcardType">
            <xs:sequence>
                <xs:element name="drivername" type="apex:drivernameType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"  use="required"/>
        </xs:complexType>
        
        <xs:element name="apex">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="paths">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="perl" type="xs:anyURI" minOccurs="0" />
                                <xs:element name="pluginScriptLibrary" type="xs:anyURI" minOccurs="0">
                                    <xs:annotation>
                                        <xs:documentation>
                                            Name of main script library. Will be searched for in the plugins path and will be concatenated to any 
                                            XML generating plugin.
                                        </xs:documentation>
                                    </xs:annotation>
                                </xs:element>
                                <xs:element name="xslt" type="xs:anyURI" minOccurs="0" >
                                    <xs:annotation>
                                        <xs:documentation>URL where the xslt scripts reside to be used for transformation of results files. This URI will be used to set the xml-stylesheet processing instruction in the results file.</xs:documentation>
                                    </xs:annotation>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

	  <xs:element name="soundcards">
                     <xs:complexType>
                         <xs:sequence>
                             <xs:element name="card" type="apex:soundcardType" minOccurs="0" maxOccurs="unbounded"/>
                         </xs:sequence>	           
                     </xs:complexType>	      
	  </xs:element>
                    
                    <xs:element name="prefixes" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="prefix" minOccurs="0" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:simpleContent>
                                            <xs:extension base="xs:anyURI">
                                                <xs:attribute name="id" use="required" type="xs:ID"></xs:attribute>
                                            </xs:extension>
                                        </xs:simpleContent>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>

                </xs:sequence>
                <xs:attribute name="version" use="required" type="xs:positiveInteger"></xs:attribute>
            </xs:complexType>
            
        </xs:element>


        
        
</xs:schema>

=== anneliesdevesse/apex/data/config/apexconfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<apex:apex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://med.kuleuven.be/exporl/apex/3.0.2/config https://gilbert.med.kuleuven.be/apex/schemas/3.0.2/apexconfig.xsd"
    xmlns:apex="http://med.kuleuven.be/exporl/apex/3.0.2/config" version="1">
    <paths>
        <perl>/usr/bin/perl</perl>
        <pluginScriptLibrary>pluginscriptlibrary.js</pluginScriptLibrary>
    </paths>
    <soundcards>
        <card id="RME">
            <drivername driver="asio">ASIO Hammerfall DSP</drivername>
            <drivername driver="portaudio">HDSP Analog Out (1+2)(1)</drivername>
        </card>
        <card id="LynxONE">
            <drivername driver="asio">LynxONE</drivername>
            <drivername driver="portaudio">LynxONE FIXME</drivername>
        </card>
        <card id="Audiophile">
            <drivername driver="asio">M-Audio Audiophile</drivername>
            <drivername driver="portaudio">M-Audio Audiophile USB</drivername>
            <drivername driver="coreaudio">M-Audio Audiophile USB</drivername>
        </card>
        <card id="SoundMax">
            <drivername driver="asio">NULL</drivername>
            <drivername driver="portaudio">SoundMAX Digital Audio</drivername>
        </card>
        <card id="default">
            <drivername driver="asio">default</drivername>
            <drivername driver="portaudio">default</drivername>
            <drivername driver="jack">default</drivername>
            <drivername driver="coreaudio">default</drivername>
        </card>
        <card id="macdefaultout">
            <drivername driver="asio">NULL</drivername>
            <drivername driver="portaudio">Built-in Output</drivername>
            <drivername driver="jack">NULL</drivername>
            <drivername driver="coreaudio">Built-in Output</drivername>
        </card>
    </soundcards>
    <prefixes>
        <prefix id="regression">file:../stimuli</prefix>
        <prefix id="speechmaterials">file:l:/speechmaterials</prefix>
        <prefix id="pictures">../../pictures</prefix>
    </prefixes>
</apex:apex>
